kutpe/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('mentors/', include('mentors.urls')),
    path('internships/', include('internships.urls')),
    path('events/', include('events.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    full_name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    country = models.CharField(max_length=255)
    gender = models.CharField(max_length=10, choices=(('Male', 'Male'), ('Female', 'Female')))
    description = models.TextField(blank=True, null=True)
    date_of_birth = models.DateTimeField(null=True, blank=True)
    image = models.ImageField(upload_to='media/user', null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.full_name

class Products(models.Model):
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    quality = models.CharField(max_length=10, choices=(('Good', 'Good'), ('Bad', 'Bad')))
    image = models.ImageField(upload_to='media/user', null=True, blank=True)


    def __str__(self):
        return f"{self.name}, price: {self.price}"

templates/profile/become_student.html
{% extends 'base.html' %}
{% block content %}
  <h1>Become a Student</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Become a Student</button>
  </form>
{% endblock %}

templates/profile/create_internship.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/mentor_profile.css' %}">

<div class="container centered-content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Управление стижировкой</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/profile/edit_profile.html
{% extends 'base2.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">

<div class="container centered-content">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h2>Изменения профиля</h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.full_name.label_tag }}
                            {{ form.full_name }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label_tag }}
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            {{ form.country.label_tag }}
                            {{ form.country }}
                        </div>
                        <div class="form-group">
                            {{ form.gender.label_tag }}
                            {{ form.gender }}
                        </div>
                        <div class="form-group">
                            {{ form.username.label_tag }}
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            {{ form.password.label_tag }}
                            {{ form.password }}
                        </div>
                        <div class="form-group">
                            {{ form.confirm_password.label_tag }}
                            {{ form.confirm_password }}
                        </div>
                        <div class="form-group">
                            {{ form.date_of_birth.label_tag }}
                            <input type="date" name="date_of_birth" id="id_date_of_birth">
                        </div>
                        <div class="form-group">
                            {{ form.description.label_tag }}
                            {{ form.description }}
                        </div>
                        <div class="form-group">
                            {{ form.education.label_tag }}
                            {{ form.education }}
                        </div>
                        <div class="form-group">
                            {{ form.image.label_tag }}
                            {{ form.image }}
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/profile/leave_contact.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
<h2>Оставить контакты для ментора {{ mentor.user.full_name }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить контакты</button>
</form>
{% endblock %}

templates/profile/manage_mentor_profile.html
{% extends "base2.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/mentor_profile.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <div class="container centered-content">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h2>Управление профилем ментора</h2>
                    </div>
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/mentor_detail.html
{% extends "base2.html" %}
{% load static %}
{% block content %}
<div class="mentor-details-container d-flex justify-content-center align-items-center">
<div class="card mentor-card col-12 col-md-4" >
        <img class="card-img-top img-fluid rounded" src="{% if mentor.image %}{{ mentor.image.url }}{% else %}https://www.vremyarozat.ru/static/images/no-photo.png{% endif %}" alt="{{ mentor.user.full_name }}">
        <div class="card-body">
            <h5 class="card-title">{{ mentor.user.full_name }}</h5>
            <p class="card-title">{{ mentor.city }}</p>
            <p class="card-title">{{ mentor.user.email }}</p>
            <p class="card-text">{{ mentor.subjects }}</p>
            <p class="card-text">{{ mentor.description }}</p>
            <p class="card-text">{{ mentor.phone_number }}</p>
            <p class="card-text">{{ mentor.format }}</p>
            <p class="card-text">{{ mentor.education }}</p>
            {% if mentor.instagram %}
                <p class="card-text">{{ mentor.instagram }}</p>
            {% else %}
            {% endif %}
            {% if mentor.telegram %}
                <p class="card-text">{{ mentor.telegram }}</p>
            {% else %}
            {% endif %}
        </div>
        <div class="card-footer">
            <a class="btn btn-primary" href="{% url 'leave_contact' mentor_id=mentor.id %}">Оставить контакты</a>
            <a class="btn btn-secondary close-button" href="{% url 'home'%}">Закрыть</a>
        </div>
    </div>
</div>
{% endblock %}

templates/profile/profile.html
{% extends 'base2.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <div class="profile-wrapper">
        <div class="profile-container">
            <div class="profile-header">
                <div class="profile-photo">
                    {% if user.image %}
                        <img src="{{ user.image.url }}" alt="User Photo">
                    {% else %}
                        <img src="https://png.pngtree.com/png-clipart/20190925/original/pngtree-no-avatar-vector-isolated-on-white-background-png-image_4979074.jpg"
                             alt="User Photo">
                    {% endif %}
                </div>
                <div class="profile-info">
                    <h1>{{ user.full_name }}</h1>
                    <p class="location">{{ user.country }}</p>
                </div>
            </div>
            <div class="profile-actions row">
                <div class="col-md-4">
                    <a class="btn btn-primary" href="{% url 'edit_profile' %}">Редактировать</a>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-primary" href="{% url 'create_internship' %}">Добавить стажировку</a>
                </div>
                <div class="col-md-4">
                    <a class="btn btn-primary" href="{% url 'become_mentor' %}">
                        {% if is_mentor %}
                            Изменить карту наставника
                        {% else %}
                            Добавить карту наставником
                        {% endif %}
                    </a>
                </div>
            </div>
            <div class="profile-details">
                <h2>Мои карточки</h2>
                <ul>
                    {% if is_mentor %}
                        <li>
                            <a href="#">{{ mentor_profile.subjects }}</a>
                            <ul>
                                <li>{{ mentor_profile.description }}</li>
                            </ul>
                        </li>
                    {% else %}
                        <li>
                            <p class="text-muted">
                                Добавьте карточку репетитора
                            </p>
                        </li>
                    {% endif %}
                </ul>
                <ul>
                    {% if is_internship %}
                        <li>
                            <a href="#">Наименоваие организации: {{ internship.organization_name }}</a>
                            <ul>
                                <li>Позиция: {{ internship.position }}</li>
                                <li>Описание: {{ internship.description }}</li>
                            </ul>
                        </li>
                    {% else %}
                        <li>
                            <p class="text-muted">
                                Добавьте карточку стажировки
                            </p></li>
                    {% endif %}
                </ul>
                <h2>О себе</h2>
                {% if user.email %}
                    <p>Email: {{ user.email }}</p>
                {% else %}
                    <p class="text-muted">
                        Пусто
                    </p>
                {% endif %}
                {% if user.gender %}
                    <p>Пол: {{ user.gender }}</p>
                {% else %}
                    <p class="text-muted">
                        Пусто
                    </p>
                {% endif %}
                {% if user.description %}
                    <p>О себе: {{ user.description }}</p>
                {% else %}
                    <p class="text-muted">
                        Пусто
                    </p>
                {% endif %}
                <h2>Образование</h2>
                {% if user.education %}
                    <p>{{ user.education }}</p>
                {% else %}
                    <p class="text-muted">
                        Пусто
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}